### ISSUE TITLE
插件功能请求

### ISSUE THREAD

**Issue by xeKapw** [Akokk0/koishi-plugin-bilibili-notify#1]
首先非常感谢本项目开发出如此简单好用的插件，居然直接扫码登录就行了，不用获取token。
我在此希望，后续版本能够添加去掉边框的功能，或者能优化显示效果，目前的样式字会比较小。
另外想问下为什么限制了只能订阅3个账号，不够用，哈哈。

**Comment by Akokk0** [comment]
非常感谢您的肯定！请问您说的边框是指可在设置中调整颜色的推送卡片背景吗，这方面的问题我会尝试优化的。对于限制3个账号是因为怕订阅账号太多会导致B站那边认为是攻击而被封禁IP一段时间，如果确实有需要之后的版本可以放开限制。另外，在使用过程中，如果您遇到什么bug请麻烦您向我反馈，我这边在测试时几乎每天都能发现新bug。最后，非常感谢您的建议

**Comment by xeKapw** [comment]
> 非常感谢您的肯定！请问您说的边框是指可在设置中调整颜色的推送卡片背景吗，这方面的问题我会尝试优化的。对于限制3个账号是因为怕订阅账号太多会导致B站那边认为是攻击而被封禁IP一段时间，如果确实有需要之后的版本可以放开限制。另外，在使用过程中，如果您遇到什么bug请麻烦您向我反馈，我这边在测试时几乎每天都能发现新bug。最后，非常感谢您的建议

蟹蟹回复。是的，就是默认粉色的那个卡片背景，主要就是希望能字够大，内容主体突出就好了。目前我订阅的以动态推送为主，几个UP发动态也不是特别频道，目前感觉良好，登录失效之类都有提示，如有遇到bug会第一时间反馈的。哦还有，不知能否做关键词屏蔽一类功能，有些up会发广告，啊哈哈。

**Comment by Akokk0** [comment]
我刚刚发布了1.0.9-alpha.0版本，您之前提到的问题都尝试着解决了一下，字体大小尽量增大了，太大了会比较难看。边框也有设置可以移除一层，如果粉色背景也移除也会比较难看。您可以先用用看，如果还是觉得小我再调整一下。对于关键词屏蔽，是动态里包含某些关键词就屏蔽还是更高级的屏蔽方法，如果是关键词或者正则那没什么问题

**Comment by xeKapw** [comment]
感谢更新，我已更新至1.1.0-alpha.0版本。我直接用自己号进行了下测试。有几个情况反馈给您。
我使用的是koishi-adapter-qq接入的koishi，使用的QQ官方bot在QQ频道内文字子频道发布推送消息。
图1是我之前使用订阅的up发布视频时的推送效果情况截图，当时使用的应该是bilibili notify的1.0.7-alpha.0或更早版本，adapter-qq应该是上一版本即4.3.1。显示效果是比较好的（除了上面为此反馈的字体大小问题）。
![Screenshot_20240125_170228](https://github.com/Akokk0/koishi-plugin-bilibili-notify/assets/39191650/6d7d24bb-d3c2-4f5c-bc7e-15a56bce0373)
图2图3是对应我将adapter-qq更新至目前最新的4.4.0，将bilibili-notify更新至最新的1.1.0-alpha.0的情况。
其中图2我从测试1进行测试，想要看看是否是因为不带图而导致bot推送的渲染图效果不佳（没完整显示缩略图）。
测试1情况：仅文本，机器人未推送。猜测可能是因为我刚刚订阅就发了这个动态所以没收到
测试2情况：仅文本，机器人成功推送，但是显示效果没之前那种全展示的情况，这个我也不清楚是什么原因导致。
测试3情况：文本+图被b站系统吞了，机器人检测到了，但推送了上一则动态（即测试2）。
测试4情况：文本+图片，机器人检测到了，但是推送了上一则动态。
测试5。。。。后面出bug了，没有发送动态也会每2分钟重复推送一次上一则动态。后面没有再测试。
![Screenshot_20240125_170236](https://github.com/Akokk0/koishi-plugin-bilibili-notify/assets/39191650/d014f0e4-262d-4aa0-8a3c-12a8737ec5ed)
![{E231824C-0353-4f06-AB26-68E272A90A85}](https://github.com/Akokk0/koishi-plugin-bilibili-notify/assets/39191650/de45e6d2-f942-4f06-bd15-521d3ddc78a0)

**Comment by Akokk0** [comment]
非常感谢您帮我测试插件。以我的理解来看，图一除了字体大小的问题以外应该是没有其他问题的。从图二开始，我需要向您确认您说的是否是`1.0.10-alpha.0`这个版本，因为我从来没有发布过`1.1.0-alpha.0`这个版本。对于缩略图显示不全的问题，是插件的问题，我会在后续版本进行修复的。对于测试1，是代码层面的问题，虽然提示了已订阅，但是会在您设置的`dynamicLoopTime`时间之后才开始检测，根据您的情况看，您应该设置的是默认值2分钟，所以这2分钟的动态都是检测不到的。对于测试2，是QQ的问题，插件渲染的图片是固定宽度的，QQ对于太宽的也就是长条形的图片就会出现这样的情况，因为出现只有一行字的动态情况比较少，做适配工作量比较大，所以这个问题还没有解决。对于情况3，4，5，应该是同一个问题，这个问题我不确定是在哪个版本出现的，但是1.0.0及以前和1.0.4以及之后的版本应该都没有这样的问题，如果您确实是在`1.0.10-alpha.0`这个版本出现的这个问题，那有可能是新bug，如果可以的话麻烦您提供一下您的插件配置信息，还需要向您确定您搭载机器人的电脑或服务器系统时间是否是`UTC+8`

**Comment by Akokk0** [comment]
非常感谢您提供的信息，目前这个bug已经在`1.0.11`修复了，应该没有问题了
