### ISSUE TITLE
获取订阅列表为空

### ISSUE THREAD

**Issue by axlmly** [Akokk0/koishi-plugin-bilibili-notify#11]
使用1.2.0（2024.3.21最新）按照教程订阅成功后，重启koishi又全部为空，查看数据库内存在数据。
使用数据库为mysql（6.0.1）

**Comment by Akokk0** [comment]
你好，方便加群吗，801338523

**Comment by axlmly** [comment]
> 你好，方便加群吗，801338523

加了，方便
