### ISSUE TITLE
推送时多次@全体成员

### ISSUE THREAD

**Issue by hui-ld** [Akokk0/koishi-plugin-bilibili-notify#13]
首先感谢大大做了如此方便的插件
![I0SQ 4O0R9M7@@QG)Z US2U](https://github.com/Akokk0/koishi-plugin-bilibili-notify/assets/112241195/4fa4584c-445e-4311-a52d-fce545197b71)
如图，使用llonebot3.20.7+koishi4.17.3+koishi-plugin-bilibili-notify1.2.3-rc.4
机器人非管理，即便如此也还是多次@全体成员，至此消息都发送失败
大概发了九条，然后重新推送了一个没有@全体成员的开播三分钟的消息，发送成功了

或许可以单独设置每个群推送时是否@全体成员？，感谢大大解惑

**Comment by Akokk0** [comment]
感谢您的使用。首先，即使没有管理员应该也不存在 `@全体成员` 消息会发送失败的问题，可以先升级 `1.2.3-rc.8` 版本试试，如果仍然无法解决可以加群 `801338523` 。对于单独设置的问题，稍微会有点麻烦，暂时没有时间写这个功能。
