### ISSUE TITLE
飞书(lark)平台支持

### ISSUE THREAD

**Issue by Lqy200004** [Akokk0/koishi-plugin-bilibili-notify#19]
预期功能：
希望插件能够增加对飞书/Lark平台的支持。

实际情况：
当在飞书中使用插件订阅命令（bili sub）时，Bot回复“暂不支持该平台”。

**Comment by Akokk0** [comment]
`1.3.2` 已支持

**Comment by Lqy200004** [comment]
可以正常使用了，十分感谢！
