### ISSUE TITLE
Onebot支持

### ISSUE THREAD

**Issue by lonelyion** [Akokk0/koishi-plugin-bilibili-notify#2]
因为历史原因我现在仍然在使用`koishi-plugin-adapter-onebot`接入koishi，但是使用`bili sub xxx`的时候会提示`暂不支持该平台`，推测可能是因为https://github.com/Akokk0/koishi-plugin-bilibili-notify/blob/2ab7134fd64e85c59dfc10d5e49219b3345b3863/src/comRegister.tsx#L319 这里没有相应的case，现有的adapter-qq目前只对企业认证开放了群聊权限，并不方便使用，所以希望新增一下Onebot的实现。

**Comment by Akokk0** [comment]
我刚刚发布了1.0.10-alpha.0版本，您可以试试新版本能不能使用，因为我这边没有onebo环境，所以无法测试。另外，如果您在使用的过程中遇到什么bug，希望您可以向我反馈。最后，非常感谢您使用本插件

**Comment by lonelyion** [comment]
添加订阅成功了，非常感谢！

有bug我再另外开issue或者pr吧www
