### ISSUE TITLE
push time设置没作用

### ISSUE THREAD

**Issue by NealScx** [Akokk0/koishi-plugin-bilibili-notify#21]
![image](https://github.com/user-attachments/assets/5e8ae753-dc1d-44f0-a003-d895ff11a164)
设置0和2小时还是偶尔出现隔30分钟推送一次的问题
![image](https://github.com/user-attachments/assets/26229360-87f2-45d1-b6dd-d1140e7db876)
![image](https://github.com/user-attachments/assets/7a6ca490-af54-4559-a9a3-f64ba5b772b4)

**Comment by Akokk0** [comment]
请问是否在此期间重启过插件或者koishi

**Comment by NealScx** [comment]
破案了  好像是这个插件的原因  谢谢
![64c9d4c1c9a4231ee882ba7122434e57](https://github.com/user-attachments/assets/f0847d75-8bcc-4dc3-b692-8c74daf8b11e)
![36857a46563c5e6015e235f1cc3b0319](https://github.com/user-attachments/assets/16bf8c9b-6f92-469e-b110-95af54b56d2d)
