### ISSUE TITLE
成功登录后发送指令回复风控校验失败，但账号未被风控

### ISSUE THREAD

**Issue by Tigrex-Dai** [Akokk0/koishi-plugin-bilibili-notify#24]
![image](https://github.com/user-attachments/assets/d2967129-89c3-4dd2-b826-9175f7eb46bf)

**Comment by Akokk0** [comment]
更改基本设置的userAgent配置，建议更换为自己浏览器的UA

**Comment by Tigrex-Dai** [comment]
谢谢！可以用了！
