### ISSUE TITLE
red支持

### ISSUE THREAD

**Issue by 114cloud** [Akokk0/koishi-plugin-bilibili-notify#4]
作者你好，我接入koishi时使用的是`koishi-plugin-adapter-red`，但是使用`bili sub`时提示`暂不支持该平台`。因为我没有群机器人权限，所以请问一下能否支持该平台。

**Comment by Akokk0** [comment]
可以的，但是需要明天晚些时候

**Comment by 114cloud** [comment]
非常感谢！

**Comment by 114cloud** [comment]
另外我还想加一个小小的功能请求，就是在开播提示之后发送一个艾特全体成员的消息。

**Comment by Akokk0** [comment]
在最新版本`1.0.14`更新了对red的支持。因为我没有red环境，所以无法进行测试，如果您在使用过程中遇到什么bug，希望您可以反馈给我，非常感谢您的使用

**Comment by 114cloud** [comment]
您好！感谢您采纳了我的建议，但是在我测试的过程中发现一个问题，在QQ群内可以正常订阅up，但不能发送推送消息，而在QQ频道内则是正常的，不知道这是否是一个bug，如果需要的话我可以提供更多信息！
![屏幕截图 2024-02-01 130307](https://github.com/Akokk0/koishi-plugin-bilibili-notify/assets/148178844/5821860b-c61b-44be-aa55-2b13a26c879e)
![屏幕截图 2024-02-01 130417](https://github.com/Akokk0/koishi-plugin-bilibili-notify/assets/148178844/b8696d56-0b44-49e2-a624-173d381da7dc)

**Comment by Akokk0** [comment]
请问，在QQ频道环境下，您使用的应该是官方机器人。在QQ群环境下，您使用的是Red是这样吗。在QQ群环境下，输入指令后机器人是否有回复，比如bili show。还需要问的是，您是否是在同一个koishi环境下同时运行官方机器人和Red，如果是，您是否只在QQ频道内进行过订阅操作

**Comment by 114cloud** [comment]
对的，在频道环境下我使用的是官方机器人，QQ群环境使用的是red环境
QQ群环境下输入指令机器人有回复，包括`bili show`和`bili status`
我是在同一个koishi环境下同时运行官方机器人和Red
我在QQ群内也进行过订阅操作，具体是我在QQ群内登录后使用`bili show`发现已订阅我自己的B站号，去B站发动态测试机器人没反应，我就使用`bili unsub`取消订阅，然后使用`bili sub`重新订阅，机器人还是没反应

**Comment by 114cloud** [comment]
抱歉这么久才回复，我在多次尝试失败后改用`adapter-onebot`接入koishi，然后就可以正常使用了，我怀疑是插件对red的支持有点问题emmm，最后还是很感谢作者开发出这么好用的插件，特别是推送卡片效果很美观

**Comment by Akokk0** [comment]
非常感谢您的肯定，刚刚已确认对red协议支持确实有一个bug，但不知道是否完全修复，如果您愿意尝试的话，我已经发布了`1.1.2`版本

**Comment by 114cloud** [comment]
刚刚测试了一下能正常使用了，遇到问题了我再新开issue吧~
