### ISSUE TITLE
功能请求：自定义开播下播提示语

### ISSUE THREAD

**Issue by 114cloud** [Akokk0/koishi-plugin-bilibili-notify#5]
作者您好，我在打开开播艾特全体功能后，在主播开播时会先发送一个艾特全体消息再发送图片，这期间有一段间隔，群友只看到一个艾特全体消息会觉得莫名其妙的，要是能自定义可能会好一点emmm

**Comment by Akokk0** [comment]
修复了一下，现在应该会在图片发送之后再艾特全体成员。如果确实需要自定义开播下播提示语会在下个版本更新
