### ISSUE TITLE
[Feature Request]: Telegram平台支持

### ISSUE THREAD

**Issue by tiehu** [Akokk0/koishi-plugin-bilibili-notify#8]
### 预期功能：
希望插件能够增加对Telegram平台的支持。

### 实际情况：
当在Telegram中使用插件订阅命令（bili sub）时，Bot回复“暂不支持该平台”。

**Comment by Akokk0** [comment]
`1.2.0-rc.1`对Telegram进行了支持，但是没有进行测试，如果遇到bug，麻烦您向我反馈，感谢您的使用

**Comment by Akokk0** [comment]
刚刚更新了`1.2.0-rc.1`，请您再订阅后，看看日志有没有输出。您的建议之后会考虑更新的

**Comment by Akokk0** [comment]
方便加QQ群吗，801338523。麻烦您看下bilibili数据库，您订阅的那个UID的platform有没有，或者数据库里面有没有数据
